baseURL = "https://rfc.fm/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "RFC.FM"
theme = "diary"

[[menu.main]]
url = "https://podcasts.apple.com/us/podcast/rfc-fm/id1573663933"
name = "sur Apple Podcast"
weight = 1

[[menu.main]]
url = "https://open.spotify.com/show/77OhWoCrN1vLanVFz70vjd"
name = "sur Spotify"
weight = 2

[[menu.main]]
url = "https://rfcfm.libsyn.com/rss"
name = "Le flux RSS à l’ancienne"
weight = 3

[[menu.main]]
url = "mailto:rfc@rfc.fm"
name = "Poser une question"
weight = 3


